export const PRODUCT_TYPES = [
  "kruszywo",
  "cement",
  "Sanitarka",
  "Ogrodzenia",
  "Wycinka",
  "Geodezja",
  "Roboty ziemne",
  "Mosty, Przepusty",
  "Mała architektura",
  "Naw. Betonowe",
  "Brukarz",
  "Przepus",
  "Place zabaw, Mała Arch.",
  "Nadzór saperski",
  "Archeologia",
  "Mury Oporowe",
  "Recykling-Stabilizacja",
  "Deska kompozytowa",
  "Zahumusowanie i odhumusowanie",
  "Pale",
  "Oznakowanie",
  "Zieleń",
  "Ekrany",
  "Nadzór przyrodniczy",
  "Naw. Zywiczne",
  "Przewierty",
  "Elektryka Teletechnika",
  "Projektanci",
  "Oznakowanie pionowe; Oznakowanie poziome",
  "Fontanna",
  "KMA",
  "Wiaty przystankowe",
  "Frezowanie",
  "Rozbiórki",
  "Profilowanie Blach",
  "Gaz",
  "Sanitarka GAZ Co",
  "Gaz CO",
  "Zimowe utrzymanie",
  "Syglanlizacje",
  "CO GAZ",
  "Sygnalizacja",
  "Montaż Wagi",
  "Sanitarka, Gaz",
];
